---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      # 指定使用我們建好的service
      serviceAccountName: aws-ecr-sa
      # 拿出 ECR 密碼來拉取 Image
      imagePullSecrets:
      - name: aws-ecr-cred
      containers:
      - name: fastapi-container
        image: "576212613996.dkr.ecr.ap-northeast-1.amazonaws.com/tf-project-api:latest"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000