apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: aws-ecr-sa
      imagePullSecrets:
        - name: aws-ecr-cred
      containers:
        - name: auth
          image: 576212613996.dkr.ecr.ap-northeast-1.amazonaws.com/tf-project-auth:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000