steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.7.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/gcp
        terraform init

  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.7.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/gcp
        terraform apply -auto-approve
    env:
      - 'TF_VAR_repo_name=${_REPO_NAME}'
      - 'TF_VAR_gcp_region=${_GCP_REGION}'
      - 'TF_VAR_gcp_project_id=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY